name: actearly
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.0.0

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  cloud_firestore: ^4.8.3 #Connect to Data Base
  get:  #translate
  quickalert:   # add this line #dialogs
  flutter_svg: 2.0.7 #icons
  google_nav_bar: ^5.0.6 #navbar

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/img/bg.png
    - lib/assets/img/bg_lenguajes.png
    - lib/assets/img/bg_login.png
    - lib/assets/img/bg_main.png
    - lib/assets/img/accept_bg.png
  fonts:
  - family: Archive
    fonts:
    - asset: lib/assets/fonts/Archivo/Archivo-ExtraBold.ttf
      weight: 800
    - asset: lib/assets/fonts/Archivo/Archivo-Bold.ttf
      weight: 700
    - asset: lib/assets/fonts/Archivo/Archivo-SemiBold.ttf
      weight: 600
    - asset: lib/assets/fonts/Archivo/Archivo-Medium.ttf
      weight: 500
    - asset: lib/assets/fonts/Archivo/Archivo-Regular.ttf
      weight: 400
      style: normal
    - asset: lib/assets/fonts/Archivo/Archivo-Light.ttf
      weight: 300
  - family: Work_Sans
    fonts:
    - asset: lib/assets/fonts/Work_Sans/WorkSans-ExtraBold.ttf
      weight: 800
    - asset: lib/assets/fonts/Work_Sans/WorkSans-Bold.ttf
      weight: 700
    - asset: lib/assets/fonts/Work_Sans/WorkSans-SemiBold.ttf
      weight: 600
    - asset: lib/assets/fonts/Work_Sans/WorkSans-Medium.ttf
      weight: 500
    - asset: lib/assets/fonts/Work_Sans/WorkSans-Regular.ttf
      weight: 400
      style: normal
    - asset: lib/assets/fonts/Work_Sans/WorkSans-Light.ttf
      weight: 300